name: ndy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

fonts: 
  - family: Inter
    fonts:
      - asset: fonts/Inter-VariableFont_slnt,wght.ttf
      - asset: fonts/Inter-Thin.ttf
        weight: 100
      - asset: fonts/Inter-ExtraLight.ttf
        weight: 200
      - asset: fonts/Inter-Light.ttf
        weight: 300
      - asset: fonts/Inter-Regular.ttf
        weight: 400
      - asset: fonts/Inter-Medium.ttf
        weight: 500
      - asset: fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: fonts/Inter-Bold.ttf
        weight: 700
      - asset: fonts/Inter-ExtraBold.ttf
        weight: 800
      - asset: fonts/Inter-Black.ttf
        weight: 900
dependencies:
  video_thumbnail: ^0.4.3
  flutter_slidable: ^0.6.0
  visibility_detector: ^0.4.0
  provider: ^6.0.5
  video_player: ^2.2.6
  camera: ^0.8.1+5
  cached_network_image: ^3.1.0
  palette_generator: ^0.3.3+2
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  uuid: ^3.0.4
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  file_picker: ^5.3.2
  audioplayers: ^4.1.0
  flutter_sound: ^9.2.13
  permission_handler: ^10.3.0
  open_file: ^3.3.1
  intl: ^0.17.0
  flutter_ffmpeg: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
