name: ndy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  uuid: ^3.0.4
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  file_picker: ^5.3.2
  ffmpeg_kit_flutter: ^5.1.0
  audioplayers: ^4.1.0
  flutter_sound: ^9.2.13
  permission_handler: ^10.3.0
  open_file: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
