name: ndy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  uuid: ^3.0.4
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
